//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Player.rc 使用
//
#define IDI_MAIN                        1
#define IDOK2                           3
#define IDI_LAST                        146
#define IDI_LRC                         147
#define IDI_NEXT                        148
#define IDI_PAUSE                       149
#define IDI_PLAY                        150
#define IDI_STOP                        151
#define IDI_BLANCE                      152
#define IDI_SLIENT                      153
#define IDI_SPEED                       154
#define IDI_VOL                         155
#define IDD_LIST                        161
#define IDD_ABOUT                       175
#define IDI_SEARCH                      178
#define IDD_EQ                          179
#define IDI_PLAYLIST                    181
#define IDI_TICK                        189
#define IDD_EFFECT                      190
#define IDD_SBV                         191
#define IDD_INPUT                       192
#define IDB_ABOUT                       193
#define IDI_LISTMANAGING                197
#define IDD_BOOKMARK                    198
#define IDD_DAYLYTIP                    199
#define IDD_OPTIONS                     200
#define IDD_OPTIONS2                    201
#define IDD_123                         202
#define IDD_CHORUS                      203
#define IDD_COMPRESSOR                  204
#define IDD_DISTORTION                  205
#define IDD_ECHO                        206
#define IDD_FLANGER                     207
#define IDD_GARGLE                      208
#define IDD_I3DL2REVERB                 209
#define IDD_REVERB                      210
#define IDD_LRCMAKER                    211
#define IDI_ARROWCIRCLE                 212
#define IDI_ARROWCIRCLEONE              213
#define IDI_ARROWCROSS                  214
#define IDI_ARROWRIGHT                  215
#define IDI_ARROWRIGHTTHREE             216
#define IDI_CROSS                       218
#define IDI_CROSS2                      219
#define IDI_DISK                        220
#define IDI_INFO                        221
#define IDI_LAST2                       223
#define IDI_LOCATE                      224
#define IDI_NEXT2                       228
#define IDI_PAUSE2                      230
#define IDI_PLAY2                       232
#define IDI_PLAYLISTMANAGE              234
#define IDI_PLUS                        235
#define IDI_READFILE                    236
#define IDI_SETTINGS                    238
#define IDI_THREETRACKBARS              241
#define IDI_TICK2                       243
#define IDI_VOLSLIENT                   245
#define IDC_LB_FILE                     1031
#define IDC_ED_NEW                      1032
#define IDC_ED_FILE                     1032
#define IDC_BT_NEW                      1033
#define IDC_BT_CANCEL                   1034
#define IDC_BT_OK                       1036
#define IDC_ST_TIP                      1037
#define IDC_LV_LISTFILE                 1038
#define IDC_ST_MAINICON                 1040
#define IDC_TB_BANDWIDTH                1045
#define IDC_CB_EQ                       1046
#define IDC_BT_RESET                    1047
#define IDC_TB2                         1048
#define IDC_TB1                         1049
#define IDC_TB3                         1050
#define IDC_TB5                         1051
#define IDC_TB4                         1052
#define IDC_TB7                         1053
#define IDC_TB6                         1054
#define IDC_TB9                         1055
#define IDC_TB8                         1056
#define IDC_TB10                        1057
#define IDC_CM                          1059
#define IDC_TAB                         1060
#define IDC_TB_SPEED                    1061
#define IDC_TB_VOL                      1062
#define IDC_TB_BLANCE                   1063
#define IDC_ST_SPEED                    1064
#define IDC_ST_BLANCE                   1065
#define IDC_ST_SPEED2                   1066
#define IDC_ST_VU                       1067
#define IDC_BT_VOL                      1068
#define IDC_ST_BLANCE3                  1069
#define IDC_ST_BLANCE2                  1069
#define IDC_ED_INPUT                    1069
#define IDC_ST_BLANCE4                  1070
#define IDC_ST_VOL2                     1070
#define IDC_ST_INPUT                    1070
#define IDC_ST_ABOUT                    1071
#define IDC_LV_BOOKMARK                 1072
#define IDC_ED_BMNAME                   1073
#define IDC_ED_BMCOMMENT                1074
#define IDC_ED_BMINDEX                  1075
#define IDC_ED_BMCLR                    1076
#define IDC_BT_BMSAVE                   1077
#define IDC_BT_BMJUMP                   1078
#define IDC_BT_BMDEL                    1079
#define IDC_ST_BMCLR                    1081
#define IDC_ST_DAYLYTIP                 1082
#define IDC_SB_SETTINGS                 1083
#define IDC_CB_DEFTEXTCODE              1086
#define IDC_CB_DISABLEVANIMATION        1088
#define IDC_CB_DISABLEWORDBREAK         1089
#define IDC_CB_DISABLEDTLRCSHANDOW      1090
#define IDC_ED_LRCDIR                   1092
#define IDC_BT_CHANGELRCDIR             1093
#define IDC_ED_LRCDIR2                  1094
#define IDC_ED_DTLRCSPACELINE           1094
#define IDC_BT_CHANGEFONT               1095
#define IDC_ED_FONTINFO                 1096
#define IDC_ED_DTLRCFONTINFO            1096
#define IDC_TB_DTLRCTRANSPARENT         1099
#define IDC_ST_DTLRCCLR1                1100
#define IDC_ST_DTLRCCLR2                1101
#define IDC_TB_REVERBMIX                1102
#define IDC_RB_SINEWAVE                 1104
#define IDC_TB_REVERBDELAY              1104
#define IDC_RB_TRIANGLEWAVE             1105
#define IDC_TB_REFLECTIONSDELAY         1105
#define IDC_TB_REVERB                   1106
#define IDC_TB_REVERBTIME               1106
#define IDC_TB_HIGHFREQRTRATIO          1107
#define IDC_TB_DECAYHFRADIO             1108
#define IDC_TB_DECAYTIME                1109
#define IDC_CB_LFOPHASE                 1110
#define IDC_TB_DIFFUSION                1110
#define IDC_CB_PANDELAY                 1111
#define IDC_TB_WETDRYMIX                1112
#define IDC_TB_DENSITY                  1112
#define IDC_TB_LFODEPTH                 1113
#define IDC_TB_HFREFERENCE              1113
#define IDC_TB_FEEDBACK                 1114
#define IDC_TB_LFOFREQUENCY             1115
#define IDC_TB_DELAY                    1116
#define IDC_CB_ENABLE                   1117
#define IDC_TB_GAIN                     1118
#define IDC_TB_ATTACK                   1119
#define IDC_TB_RELEASE                  1120
#define IDC_TB_THRESHOLD                1121
#define IDC_TB_RATIO                    1122
#define IDC_TB_PREDELAY                 1123
#define IDC_TB_EDGE                     1124
#define IDC_TB_CENTERFREQUENCY          1125
#define IDC_TB_PRELOWPASSCUTOFF         1126
#define IDC_TB_LEFTDELAY                1127
#define IDC_TB_RIGHTDELAY               1128
#define IDC_TB_RATEHZ                   1129
#define IDC_TB_ROOM                     1130
#define IDC_TB_ROOMHF                   1131
#define IDC_TB_ROOMROLLOFFFACTOR        1132
#define IDC_TB_REFLECTIONS              1133
#define IDC_BT_REFRESHDEV               1135
#define IDC_CB_DEVICES                  1138
#define IDC_RICHEDIT21                  1139
#define IDC_RE_LRCMAKER                 1139
#define IDC_CHECK1                      1140
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        246
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
